### ISSUE TITLE
Stats per level.

### ISSUE THREAD

**Issue by FatGrandpa007** [iThorgrim-Hub/lua-parangon#1]
So I've been trying to edit how many stats 1 point gives. 
But I've been unsuccessful so far, any help would be very much appreciated.

I might be doing it wrong if it's possible at all.
++ for making this btw, super amazing feature.

Best regards, Milo.

**Comment by iThorgrim-Hub** [comment]
Hey,

You want to set up that with 1 paragon point for example it gains +2 in strength? instead of +1?

**Comment by FatGrandpa007** [comment]
Yeah exactly, more then that though but yeah like that, is that possible?

**Comment by iThorgrim-Hub** [comment]
Then, yes it is possible but not with the version of the paragon system currently put online, I would have to make an update to be able to parameterize that ^^

**Comment by FatGrandpa007** [comment]
That would be amazing, I'm working on a project with above blizzlike rates and stats and really wanna use your module, its too awesome to pass on. So if that's a future possibility we would be stoked and others too I bet

**Comment by iThorgrim-Hub** [comment]
I finish working on the mythic module and I do an update as soon as possible :)

**Comment by FatGrandpa007** [comment]
Thanks, really appreciate it 🙏🏻
